### ISSUE TITLE
java.io.NotSerializableException: org.drools.impl.adapters.KnowledgeBaseAdapter

### ISSUE THREAD

**Issue by jkwebster** [paulovmr/engine-drools#3]
Hi,it seems that org.drools.impl.adapters.KnowledgeBaseAdapter should not be serialized.

java.io.NotSerializableException: org.drools.impl.adapters.KnowledgeBaseAdapter
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at com.ruleengine.RuleEngineBuilder.persistKnowledgeBase(RuleEngineBuilder.java:108)
	at com.ruleengine.RuleEngineBuilder.loadRules(RuleEngineBuilder.java:64)
	at com.ruleengine.RuleEngine.<init>(RuleEngine.java:14)
	at com.creditlimit.CreditLimiteChecker.refreshRules(CreditLimiteChecker.java:33)
	at com.creditlimit.CreditLimiteChecker.<init>(CreditLimiteChecker.java:23)
	at com.creditlimit.CreditLimitCheckerTest.<init>(CreditLimitCheckerTest.java:20)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:202)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:251)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:248)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by danilodeLuca** [comment]
Hello,

This problem has been corrected. Some months ago we opened one issue to drools team(https://groups.google.com/forum/#!topic/drools-setup/rmNO0Jsr7mk) and we were wating for the new release.... after that i forget to make the new pull request with the adjustments.

Thx,

Danilo
